### ISSUE TITLE
Corrupted dnp3_slave_all.xml file in download

### ISSUE THREAD

**Issue by jocamill** [openfmb/turnkey-dtech-demo-2016#3]
When I tried running the:
 dnp3testset -S -F dnp3_slave_all.xml
 step, it failed with the following error:
 loadXmlInto: Load file failed on: dnp3_slave_all.xml - Error document empty. At 0:0, 0
 I looked in the file and it contained a HUGE amount of garbage output, a little at the beginning before the <SlaveTestSet> tag but a LOT after the </SlaveTestSet> closing tag.

reported by Dwayne Bradley

**Comment by openfmb** [comment]
File has been removed and replaced dnp3_slave_default.xml. Closing.
