### ISSUE TITLE
OpenFMB 2016 UI improvement

### ISSUE THREAD

**Issue by dclawrence55** [openfmb/turnkey-dtech-demo-2016#5]
1. Trip/Close testing. Is it true that when the battery reaches 50% SOC it still says "is charging", but there is not kW flow?
2. Can you remove some of the white space in the UI, so that it fits on 1 screen better?
3. On the Terminal views...is there a way to label each one with its identity. The LoadSim is the only 1 showing publish rate. Can the others also post something to the terminal window?

**Comment by openfmb** [comment]
#1  closing.  
#2  closing
#3  closing.  There does not appear an easy way to label the terminal windows.  Logging in currently enabled for errors only.
